import { DM_Sans, Inter, Teko, Roboto_Condensed } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const dm_sans = DM_Sans({ subsets: ["latin"] });
const roboto_condensed = Roboto_Condensed({ subsets: ["latin"] });

export const metadata = {
  title: "UiFry",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto_condensed.className}>{children}</body>
    </html>
  );
}
